server:
  port: 8080

spring:
  application:
    name: CustomerApplication
  #velocity:
    #resource-loader-path: classpath:/templates/

  zipkin:
    base-url: http://localhost:9411
  datasource:
    username: 'admin'
    url: jdbc:postgresql://localhost:5432/customerDatabase
    password: "admin"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: rajamuneeb127@gmail.com
    password: 'lecdavcjzzxmogsr'
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true



