server:
  port: 8082
spring:
  application:
    name: OrderApplication
  zipkin:
    base-url: http://localhost:9411

  data:
    mongodb:
      host: localhost
      port: 27017
      database: OrderDb
      auto-index-creation: true

logging:
  file:
    name: mongod.log
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true



