spring:
  application:
    name: eureka-server


server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  file:
    path: /home/muneeb/log
    name: eureka-server.log
  level:
    root: info
    eureka : info

